CC = gcc
CFLAGS = -Wall -Wextra -Werror
TARGET = ft_display_file

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	rm -f $(TARGET)

fclean: clean
	rm -f $(TARGET)

